services:
  db:
   image: postgres:17
   environment:
     POSTGRES_DB: ${DJANGO_DATABASE_NAME}
     POSTGRES_USER: ${DJANGO_DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DJANGO_DEBUG}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DJANGO_DATABASE_ENGINE}
     DATABASE_NAME: ${DJANGO_DATABASE_NAME}
     DATABASE_USERNAME: ${DJANGO_DATABASE_USERNAME}
 
     DATABASE_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
     DATABASE_HOST: ${DJANGO_DATABASE_HOST}
     DATABASE_PORT: ${DJANGO_DATABASE_PORT}
    depends_on:
      - db
    env_file:
      - .env
    command: uv run manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: ["npm", "run", "dev", "---", "--host"]

volumes:
  postgres_data: